version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - POSTGRES_USER=quentin_lee
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city_bikes_back_dev
    networks:
      - mynetwork
  db:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=quentin_lee
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city_bikes_back_dev
      - LANG=en_US.utf8
    networks:
      - mynetwork
        #      - POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 1s
      retries: 5
networks:
  mynetwork:
